/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package db.ui;

import db.entity.Driver;
import db.dao.DriverDAO;
import db.validate.DriverValidate;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.plaf.basic.BasicTreeUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pranavan
 */
public class DriverWindow extends javax.swing.JFrame {

    /**
     * Creates new form DriverUI
     */
    public DriverWindow() {
        initComponents();
        idEditLabel.setVisible(false);
        idEditTextField.setVisible(false);
        nameEditLabel.setVisible(false);
        nameEditTextField.setVisible(false);
        addressEditLabel.setVisible(false);
        addressEditTextField.setVisible(false);
        telenoEditLabel.setVisible(false);
        teleNoEditTextField.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        driverTab = new javax.swing.JTabbedPane();
        addDriverTab = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        telephoneNoLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        telephoneNoTextField = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        save = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        editDriverTab = new javax.swing.JPanel();
        idEditSearchLabel = new javax.swing.JLabel();
        idTextFieldEdit = new javax.swing.JTextField();
        goEdit = new javax.swing.JButton();
        exitEditButton = new javax.swing.JButton();
        idEditLabel = new javax.swing.JLabel();
        nameEditLabel = new javax.swing.JLabel();
        addressEditLabel = new javax.swing.JLabel();
        telenoEditLabel = new javax.swing.JLabel();
        idEditTextField = new javax.swing.JTextField();
        nameEditTextField = new javax.swing.JTextField();
        addressEditTextField = new javax.swing.JTextField();
        teleNoEditTextField = new javax.swing.JTextField();
        deleteDriverTab = new javax.swing.JPanel();
        idDeleteLabel = new javax.swing.JLabel();
        idDeleteTextField = new javax.swing.JTextField();
        deleteDeleteButton = new javax.swing.JButton();
        exitDeleteButton = new javax.swing.JButton();
        nameDeleteLabel = new javax.swing.JLabel();
        nameDeletetextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        deleteTable = new javax.swing.JTable();
        deleteGoButton = new javax.swing.JButton();
        viewDriverTab = new javax.swing.JPanel();
        nameViewLabel = new javax.swing.JLabel();
        nameViewTextField = new javax.swing.JTextField();
        viewGoButtonField = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        idViewLabel = new javax.swing.JLabel();
        idViewTextField = new javax.swing.JTextField();
        viewExitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));

        driverTab.setPreferredSize(new java.awt.Dimension(613, 400));

        idLabel.setText("ID");

        nameLabel.setText("Name");

        addressLabel.setText("Address");

        telephoneNoLabel.setText("Telephone No");

        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        addressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextFieldActionPerformed(evt);
            }
        });

        telephoneNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telephoneNoTextFieldActionPerformed(evt);
            }
        });

        clear.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        save.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addDriverTabLayout = new javax.swing.GroupLayout(addDriverTab);
        addDriverTab.setLayout(addDriverTabLayout);
        addDriverTabLayout.setHorizontalGroup(
            addDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDriverTabLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(addDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addDriverTabLayout.createSequentialGroup()
                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addDriverTabLayout.createSequentialGroup()
                        .addGroup(addDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addDriverTabLayout.createSequentialGroup()
                                    .addComponent(idLabel)
                                    .addGap(104, 104, 104))
                                .addGroup(addDriverTabLayout.createSequentialGroup()
                                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(49, 49, 49)))
                            .addGroup(addDriverTabLayout.createSequentialGroup()
                                .addGroup(addDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telephoneNoLabel))
                                .addGap(49, 49, 49)))
                        .addGroup(addDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addressTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                            .addComponent(nameTextField)
                            .addComponent(idTextField)
                            .addComponent(telephoneNoTextField))))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        addDriverTabLayout.setVerticalGroup(
            addDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDriverTabLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(addDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(addDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addDriverTabLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(nameLabel)
                        .addGap(20, 20, 20)
                        .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addDriverTabLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(addDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addDriverTabLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(telephoneNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addDriverTabLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(telephoneNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(addDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        driverTab.addTab("ADD", addDriverTab);

        idEditSearchLabel.setText("ID");

        idTextFieldEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldEditActionPerformed(evt);
            }
        });

        goEdit.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        goEdit.setText("Go");
        goEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goEditActionPerformed(evt);
            }
        });

        exitEditButton.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        exitEditButton.setText("EXIT");
        exitEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitEditButtonActionPerformed(evt);
            }
        });

        idEditLabel.setText("ID");

        nameEditLabel.setText("Name");

        addressEditLabel.setText("Address");

        telenoEditLabel.setText("TelephoneNo");

        nameEditTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameEditTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editDriverTabLayout = new javax.swing.GroupLayout(editDriverTab);
        editDriverTab.setLayout(editDriverTabLayout);
        editDriverTabLayout.setHorizontalGroup(
            editDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDriverTabLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(editDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exitEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(editDriverTabLayout.createSequentialGroup()
                        .addGroup(editDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editDriverTabLayout.createSequentialGroup()
                                .addGroup(editDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addressEditLabel)
                                    .addComponent(telenoEditLabel))
                                .addGap(34, 34, 34)
                                .addGroup(editDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameEditTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(teleNoEditTextField)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editDriverTabLayout.createSequentialGroup()
                                .addGroup(editDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editDriverTabLayout.createSequentialGroup()
                                            .addComponent(idEditSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(50, 50, 50))
                                        .addGroup(editDriverTabLayout.createSequentialGroup()
                                            .addComponent(idEditLabel)
                                            .addGap(86, 86, 86)))
                                    .addGroup(editDriverTabLayout.createSequentialGroup()
                                        .addComponent(nameEditLabel)
                                        .addGap(70, 70, 70)))
                                .addGroup(editDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addressEditTextField)
                                    .addComponent(idEditTextField)
                                    .addComponent(idTextFieldEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))))
                        .addGap(47, 47, 47)
                        .addComponent(goEdit)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        editDriverTabLayout.setVerticalGroup(
            editDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDriverTabLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(editDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idEditSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idTextFieldEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(editDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idEditLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idEditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(editDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameEditLabel)
                    .addComponent(addressEditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(editDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressEditLabel)
                    .addComponent(nameEditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telenoEditLabel)
                    .addComponent(teleNoEditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(exitEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        driverTab.addTab("EDIT", editDriverTab);

        idDeleteLabel.setText("ENTER ID");

        deleteDeleteButton.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        deleteDeleteButton.setText("Delete");
        deleteDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDeleteButtonActionPerformed(evt);
            }
        });

        exitDeleteButton.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        exitDeleteButton.setText("Exit");
        exitDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitDeleteButtonActionPerformed(evt);
            }
        });

        nameDeleteLabel.setText("ENTER NAME");

        deleteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Address", "Tele No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(deleteTable);

        deleteGoButton.setFont(new java.awt.Font("Andalus", 1, 12)); // NOI18N
        deleteGoButton.setText("GO");
        deleteGoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteGoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deleteDriverTabLayout = new javax.swing.GroupLayout(deleteDriverTab);
        deleteDriverTab.setLayout(deleteDriverTabLayout);
        deleteDriverTabLayout.setHorizontalGroup(
            deleteDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteDriverTabLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(deleteDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idDeleteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameDeleteLabel))
                .addGap(18, 18, 18)
                .addGroup(deleteDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idDeleteTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(nameDeletetextField))
                .addGap(44, 44, 44)
                .addComponent(deleteGoButton)
                .addGap(185, 185, 185))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteDriverTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteDeleteButton)
                .addGap(33, 33, 33)
                .addComponent(exitDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
            .addGroup(deleteDriverTabLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deleteDriverTabLayout.setVerticalGroup(
            deleteDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteDriverTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deleteDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idDeleteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idDeleteTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(deleteDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameDeletetextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameDeleteLabel)
                    .addComponent(deleteGoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(deleteDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        driverTab.addTab("DELETE", deleteDriverTab);

        nameViewLabel.setText("Enter Driver Name");

        nameViewTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameViewTextFieldActionPerformed(evt);
            }
        });

        viewGoButtonField.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        viewGoButtonField.setText("GO");
        viewGoButtonField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewGoButtonFieldActionPerformed(evt);
            }
        });

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Address", "Tele No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(resultTable);

        idViewLabel.setText("Enter Driver ID");

        idViewTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idViewTextFieldActionPerformed(evt);
            }
        });

        viewExitButton.setFont(new java.awt.Font("Andalus", 1, 12)); // NOI18N
        viewExitButton.setText("Exit");

        javax.swing.GroupLayout viewDriverTabLayout = new javax.swing.GroupLayout(viewDriverTab);
        viewDriverTab.setLayout(viewDriverTabLayout);
        viewDriverTabLayout.setHorizontalGroup(
            viewDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewDriverTabLayout.createSequentialGroup()
                .addGroup(viewDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewDriverTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(viewDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idViewLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameViewLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addGap(54, 54, 54)
                        .addGroup(viewDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameViewTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(idViewTextField))
                        .addGap(42, 42, 42)
                        .addComponent(viewGoButtonField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewDriverTabLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewDriverTabLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(viewExitButton)
                .addGap(63, 63, 63))
        );
        viewDriverTabLayout.setVerticalGroup(
            viewDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewDriverTabLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(viewDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idViewTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(viewDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameViewTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewGoButtonField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(viewExitButton)
                .addGap(35, 35, 35))
        );

        driverTab.addTab("VIEW", viewDriverTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(driverTab, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(driverTab, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextFieldActionPerformed

    }//GEN-LAST:event_addressTextFieldActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void telephoneNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telephoneNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telephoneNoTextFieldActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        idTextField.setText("");
        nameTextField.setText("");
        addressTextField.setText("");
        telephoneNoTextField.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void idTextFieldEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldEditActionPerformed

    private void goEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goEditActionPerformed
        Integer id = 0;
        try {
            id = Integer.parseInt(idTextFieldEdit.getText().trim());
        } catch (NumberFormatException numberFormatException) {
            numberFormatException.printStackTrace();
        }

        if (DriverDAO.isExistDriver(id)) {
            idEditLabel.setVisible(true);
            idEditTextField.setVisible(true);
            idEditTextField.setText(id.toString());
            idEditTextField.setEditable(false);
            idEditTextField.setEnabled(false);
            Driver driver = DriverDAO.getDriver(id);
            System.out.println(driver.getId().getName());
            nameEditLabel.setVisible(true);
            nameEditTextField.setVisible(true);
            addressEditLabel.setVisible(true);
            addressEditTextField.setVisible(true);
            telenoEditLabel.setVisible(true);
            teleNoEditTextField.setVisible(true);
           // DriverDAO.updateData(id, nameEditTextField.getText().trim(), addressEditTextField.getText().trim(), teleNoEditTextField.getText().trim());
            //JOptionPane.showMessageDialog(null, "Record updated", null, JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "There is no coach with given id", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_goEditActionPerformed

    private void viewTable(List list) {
        String referenceNo = nameViewTextField.getText().trim();
        Vector<String> tableHeaders = new Vector<String>();
        Vector tableData = new Vector();

        tableHeaders.add("ID");
        tableHeaders.add("Name");
        tableHeaders.add("Address");
        tableHeaders.add("Tele No");

        if (list != null) {
            for (Object o : list) {
                Driver driver = (Driver) o;

                Vector<Object> oneRow = new Vector<Object>();
                oneRow.add(driver.getId().getId());
                oneRow.add(driver.getId().getName());
                oneRow.add(driver.getAddress());
                oneRow.add(driver.getTpNo());

                tableData.add(oneRow);
            }

            resultTable.setModel(new DefaultTableModel(tableData, tableHeaders));
        } else {

        }
    }
    private void viewGoButtonFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewGoButtonFieldActionPerformed
        // TODO add your handling code here:
        if (!nameViewTextField.getText().trim().equals("") || !idViewTextField.getText().trim().equals("")) {
            viewTable(DriverDAO.viewDrivers(nameViewTextField.getText().trim(), Integer.parseInt(idViewTextField.getText().trim())));
        } else {
            JOptionPane.showMessageDialog(null, "Please Eneter values for Name or ID", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_viewGoButtonFieldActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        if (DriverValidate.idValidate(idTextField.getText().trim())) {
            if (DriverValidate.nameValidate(nameTextField.getText().trim())) {

                DriverDAO.addData(Integer.parseInt(idTextField.getText().trim()), nameTextField.getText().trim(), addressTextField.getText().trim(), telephoneNoTextField.getText().trim());
            }
        }


    }//GEN-LAST:event_saveActionPerformed

    private void exitEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitEditButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitEditButtonActionPerformed

    private void nameEditTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameEditTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameEditTextFieldActionPerformed

    private void exitDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitDeleteButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitDeleteButtonActionPerformed

    private void deleteDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDeleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteDeleteButtonActionPerformed

    private void idViewTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idViewTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idViewTextFieldActionPerformed

    private void nameViewTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameViewTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameViewTextFieldActionPerformed

    private void deleteGoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteGoButtonActionPerformed
        if (!nameDeletetextField.getText().trim().equals("") || !idDeleteTextField.getText().trim().equals("")) {
            delTable(DriverDAO.viewDrivers(nameDeletetextField.getText().trim(), Integer.parseInt(idDeleteTextField.getText().trim())));
        } else {
            JOptionPane.showMessageDialog(null, "Please Eneter values for Name or ID", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteGoButtonActionPerformed

    private void delTable(List list) {
        String referenceNo = nameViewTextField.getText().trim();
        Vector<String> tableHeaders = new Vector<String>();
        Vector tableData = new Vector();

        tableHeaders.add("ID");
        tableHeaders.add("Name");
        tableHeaders.add("Address");
        tableHeaders.add("Tele No");

        if (list != null) {
            for (Object o : list) {
                Driver driver = (Driver) o;

                Vector<Object> oneRow = new Vector<Object>();
                oneRow.add(driver.getId().getId());
                oneRow.add(driver.getId().getName());
                oneRow.add(driver.getAddress());
                oneRow.add(driver.getTpNo());

                tableData.add(oneRow);
            }

            deleteTable.setModel(new DefaultTableModel(tableData, tableHeaders));
        } else {

        }

        ListSelectionModel selectionModel = deleteTable.getSelectionModel();
        selectionModel.setSelectionInterval(0, 0);
        selectionModel.addListSelectionListener(deleteTable);

        selectionModel.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                int OPTION = JOptionPane.showConfirmDialog(null, "Do you want to delete this record!!!", "Delete confirmation", JOptionPane.WARNING_MESSAGE);

                if (OPTION == JOptionPane.YES_OPTION) {
                    Driver driver = (Driver) e.getSource();
                    //System.out.println(driver.getId().getId());
                    JOptionPane.showMessageDialog(null, "" + driver.getId().getId(), "xxx", JOptionPane.INFORMATION_MESSAGE);
                    //DriverDAO.deleteData(driver.getId().getId());
                }
            }

        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addDriverTab;
    private javax.swing.JLabel addressEditLabel;
    private javax.swing.JTextField addressEditTextField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JButton clear;
    private javax.swing.JButton deleteDeleteButton;
    private javax.swing.JPanel deleteDriverTab;
    private javax.swing.JButton deleteGoButton;
    private javax.swing.JTable deleteTable;
    private javax.swing.JTabbedPane driverTab;
    private javax.swing.JPanel editDriverTab;
    private javax.swing.JButton exit;
    private javax.swing.JButton exitDeleteButton;
    private javax.swing.JButton exitEditButton;
    private javax.swing.JButton goEdit;
    private javax.swing.JLabel idDeleteLabel;
    private javax.swing.JTextField idDeleteTextField;
    private javax.swing.JLabel idEditLabel;
    private javax.swing.JLabel idEditSearchLabel;
    private javax.swing.JTextField idEditTextField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JTextField idTextFieldEdit;
    private javax.swing.JLabel idViewLabel;
    private javax.swing.JTextField idViewTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nameDeleteLabel;
    private javax.swing.JTextField nameDeletetextField;
    private javax.swing.JLabel nameEditLabel;
    private javax.swing.JTextField nameEditTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel nameViewLabel;
    private javax.swing.JTextField nameViewTextField;
    private javax.swing.JTable resultTable;
    private javax.swing.JButton save;
    private javax.swing.JTextField teleNoEditTextField;
    private javax.swing.JLabel telenoEditLabel;
    private javax.swing.JLabel telephoneNoLabel;
    private javax.swing.JTextField telephoneNoTextField;
    private javax.swing.JPanel viewDriverTab;
    private javax.swing.JButton viewExitButton;
    private javax.swing.JButton viewGoButtonField;
    // End of variables declaration//GEN-END:variables
}
