/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package db.ui;

import db.entity.Bill;
import db.entity.Driver;
import db.entity.DriverId;
import db.dao.DriverDAO;
import db.util.HibernateUtil;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;

/**
 *
 * @author Pranavan
 */
public class DriverWindow extends javax.swing.JFrame {

    /**
     * Creates new form DriverUI
     */
    public DriverWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        driverTab = new javax.swing.JTabbedPane();
        addDriverTab = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        telephoneNoLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        nameTextField = new javax.swing.JTextField();
        addressTextField = new javax.swing.JTextField();
        telephoneNoTextField = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        save = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        editDriverTab = new javax.swing.JPanel();
        idEditSearchLabel = new javax.swing.JLabel();
        idTextFieldEdit = new javax.swing.JTextField();
        goEdit = new javax.swing.JButton();
        exitEditButton = new javax.swing.JButton();
        idEditLabel = new javax.swing.JLabel();
        nameEditLabel = new javax.swing.JLabel();
        addressEditLabel = new javax.swing.JLabel();
        telenoEditLabel = new javax.swing.JLabel();
        idEditTextField = new javax.swing.JTextField();
        nameEditTextField = new javax.swing.JTextField();
        addressEditTextField = new javax.swing.JTextField();
        teleNoEditTextField = new javax.swing.JTextField();
        deleteDriverTab = new javax.swing.JPanel();
        idDeleteLabel = new javax.swing.JLabel();
        idDeleteTextField = new javax.swing.JTextField();
        deleteDeleteButton = new javax.swing.JButton();
        exitDeleteButton = new javax.swing.JButton();
        viewDriverTab = new javax.swing.JPanel();
        idViewLabel = new javax.swing.JLabel();
        idViewTextField = new javax.swing.JTextField();
        viewGoButtonField = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));

        driverTab.setPreferredSize(new java.awt.Dimension(613, 400));

        idLabel.setText("ID");

        nameLabel.setText("Name");

        addressLabel.setText("Address");

        telephoneNoLabel.setText("Telephone No");

        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        addressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextFieldActionPerformed(evt);
            }
        });

        telephoneNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telephoneNoTextFieldActionPerformed(evt);
            }
        });

        clear.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        save.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addDriverTabLayout = new javax.swing.GroupLayout(addDriverTab);
        addDriverTab.setLayout(addDriverTabLayout);
        addDriverTabLayout.setHorizontalGroup(
            addDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDriverTabLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(addDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addDriverTabLayout.createSequentialGroup()
                        .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addDriverTabLayout.createSequentialGroup()
                            .addComponent(telephoneNoLabel)
                            .addGap(101, 101, 101)
                            .addComponent(telephoneNoTextField))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addDriverTabLayout.createSequentialGroup()
                            .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(101, 101, 101)
                            .addComponent(addressTextField))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addDriverTabLayout.createSequentialGroup()
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(101, 101, 101)
                            .addComponent(nameTextField))
                        .addGroup(addDriverTabLayout.createSequentialGroup()
                            .addComponent(idLabel)
                            .addGap(156, 156, 156)
                            .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        addDriverTabLayout.setVerticalGroup(
            addDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDriverTabLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(addDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addDriverTabLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(idLabel))
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(addDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addDriverTabLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(nameLabel))
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(addDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addDriverTabLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telephoneNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telephoneNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(addDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        driverTab.addTab("ADD", addDriverTab);

        idEditSearchLabel.setText("ID");

        idTextFieldEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldEditActionPerformed(evt);
            }
        });

        goEdit.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        goEdit.setText("Go");
        goEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goEditActionPerformed(evt);
            }
        });

        exitEditButton.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        exitEditButton.setText("EXIT");
        exitEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitEditButtonActionPerformed(evt);
            }
        });

        idEditLabel.setText("ID");

        nameEditLabel.setText("Name");

        addressEditLabel.setText("Address");

        telenoEditLabel.setText("TelephoneNo");

        nameEditTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameEditTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editDriverTabLayout = new javax.swing.GroupLayout(editDriverTab);
        editDriverTab.setLayout(editDriverTabLayout);
        editDriverTabLayout.setHorizontalGroup(
            editDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDriverTabLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(editDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editDriverTabLayout.createSequentialGroup()
                        .addComponent(idEditLabel)
                        .addGap(140, 140, 140)
                        .addComponent(idEditTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editDriverTabLayout.createSequentialGroup()
                        .addComponent(idEditSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(idTextFieldEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editDriverTabLayout.createSequentialGroup()
                        .addComponent(nameEditLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addressEditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editDriverTabLayout.createSequentialGroup()
                        .addGroup(editDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressEditLabel)
                            .addComponent(telenoEditLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(editDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(teleNoEditTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(nameEditTextField))))
                .addGroup(editDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editDriverTabLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(goEdit)
                        .addContainerGap(186, Short.MAX_VALUE))
                    .addGroup(editDriverTabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148))))
        );
        editDriverTabLayout.setVerticalGroup(
            editDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editDriverTabLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(editDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idEditSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idTextFieldEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goEdit))
                .addGap(35, 35, 35)
                .addGroup(editDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idEditLabel)
                    .addComponent(idEditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(editDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameEditLabel)
                    .addComponent(addressEditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(editDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressEditLabel)
                    .addComponent(nameEditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(editDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editDriverTabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(exitEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(editDriverTabLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(editDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telenoEditLabel)
                            .addComponent(teleNoEditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        driverTab.addTab("EDIT", editDriverTab);

        idDeleteLabel.setText("ENTER ID");

        deleteDeleteButton.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        deleteDeleteButton.setText("Delete");
        deleteDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDeleteButtonActionPerformed(evt);
            }
        });

        exitDeleteButton.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        exitDeleteButton.setText("Exit");
        exitDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deleteDriverTabLayout = new javax.swing.GroupLayout(deleteDriverTab);
        deleteDriverTab.setLayout(deleteDriverTabLayout);
        deleteDriverTabLayout.setHorizontalGroup(
            deleteDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteDriverTabLayout.createSequentialGroup()
                .addGroup(deleteDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(deleteDriverTabLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exitDeleteButton))
                    .addGroup(deleteDriverTabLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(idDeleteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(idDeleteTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                        .addGap(29, 29, 29)
                        .addComponent(deleteDeleteButton)))
                .addGap(188, 188, 188))
        );
        deleteDriverTabLayout.setVerticalGroup(
            deleteDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteDriverTabLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(deleteDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idDeleteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idDeleteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteDeleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(exitDeleteButton)
                .addGap(52, 52, 52))
        );

        driverTab.addTab("DELETE", deleteDriverTab);

        idViewLabel.setText("Enter Driver ID");

        viewGoButtonField.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        viewGoButtonField.setText("GO");
        viewGoButtonField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewGoButtonFieldActionPerformed(evt);
            }
        });

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Address", "Tele No"
            }
        ));
        jScrollPane1.setViewportView(resultTable);

        javax.swing.GroupLayout viewDriverTabLayout = new javax.swing.GroupLayout(viewDriverTab);
        viewDriverTab.setLayout(viewDriverTabLayout);
        viewDriverTabLayout.setHorizontalGroup(
            viewDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewDriverTabLayout.createSequentialGroup()
                .addGroup(viewDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewDriverTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(idViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idViewTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(viewGoButtonField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewDriverTabLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        viewDriverTabLayout.setVerticalGroup(
            viewDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewDriverTabLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(viewDriverTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idViewTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewGoButtonField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        driverTab.addTab("VIEW", viewDriverTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(driverTab, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(driverTab, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextFieldActionPerformed

    }//GEN-LAST:event_addressTextFieldActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void telephoneNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telephoneNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telephoneNoTextFieldActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        idTextField.setText("");
        nameTextField.setText("");
        addressTextField.setText("");
        telephoneNoTextField.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void idTextFieldEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldEditActionPerformed

    private void goEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goEditActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_goEditActionPerformed

    private void viewTable(List list){
        String referenceNo = idViewTextField.getText().trim();
        Vector<String> tableHeaders = new Vector<String>();
        Vector tableData = new Vector();
        
        tableHeaders.add("ID");
        tableHeaders.add("Name");
        tableHeaders.add("Address");
        tableHeaders.add("Tele No");

        
        if (list != null)     {
            for (Object o : list) {
                Driver driver = (Driver) o;
                
                Vector<Object> oneRow = new Vector<Object>();
                oneRow.add(driver.getId().getId());
                oneRow.add(driver.getId().getName());
                oneRow.add(driver.getAddress());
                oneRow.add(driver.getTpNo());
                
                tableData.add(oneRow);
            }
            
            System.out.println("I am here");
        resultTable.setModel(new DefaultTableModel(tableData, tableHeaders));
        }
        else {
            
        }
    }
    private void viewGoButtonFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewGoButtonFieldActionPerformed
        // TODO add your handling code here:
        if (!idViewTextField.getText().trim().equals("")) {
            System.out.println("Pranavan You are here");
            viewTable(DriverDAO.viewDrivers(idViewTextField.getText().trim()));
        } else {
            JOptionPane.showMessageDialog(null, "Searching Drivers", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_viewGoButtonFieldActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        DriverDAO.addData(Integer.parseInt(idTextField.getText().trim()),nameTextField.getText().trim(),addressTextField.getText().trim(),telephoneNoTextField.getText().trim());
    }//GEN-LAST:event_saveActionPerformed

    private void exitEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitEditButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitEditButtonActionPerformed

    private void nameEditTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameEditTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameEditTextFieldActionPerformed

    private void exitDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitDeleteButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitDeleteButtonActionPerformed

    private void deleteDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDeleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteDeleteButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addDriverTab;
    private javax.swing.JLabel addressEditLabel;
    private javax.swing.JTextField addressEditTextField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JButton clear;
    private javax.swing.JButton deleteDeleteButton;
    private javax.swing.JPanel deleteDriverTab;
    private javax.swing.JTabbedPane driverTab;
    private javax.swing.JPanel editDriverTab;
    private javax.swing.JButton exit;
    private javax.swing.JButton exitDeleteButton;
    private javax.swing.JButton exitEditButton;
    private javax.swing.JButton goEdit;
    private javax.swing.JLabel idDeleteLabel;
    private javax.swing.JTextField idDeleteTextField;
    private javax.swing.JLabel idEditLabel;
    private javax.swing.JLabel idEditSearchLabel;
    private javax.swing.JTextField idEditTextField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JTextField idTextFieldEdit;
    private javax.swing.JLabel idViewLabel;
    private javax.swing.JTextField idViewTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameEditLabel;
    private javax.swing.JTextField nameEditTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTable resultTable;
    private javax.swing.JButton save;
    private javax.swing.JTextField teleNoEditTextField;
    private javax.swing.JLabel telenoEditLabel;
    private javax.swing.JLabel telephoneNoLabel;
    private javax.swing.JTextField telephoneNoTextField;
    private javax.swing.JPanel viewDriverTab;
    private javax.swing.JButton viewGoButtonField;
    // End of variables declaration//GEN-END:variables
}
