/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package db.ui;

import db.dao.BillDAO;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author DELL
 */
public class MainWindow extends javax.swing.JFrame {
    private boolean loginSuccess = false;
    private int status = 0;
     private static MainWindow mainWindow = null;
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/db/Image/Bus.png")));
       
        initComponents();
         Dimension screensize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension windowsize = getSize();
        this.setBounds((screensize.width - windowsize.width) / 2, 0, windowsize.width, windowsize.height);
    }
    
    public static MainWindow create() {
        if (mainWindow == null) {
            mainWindow = new MainWindow();
        }
        return mainWindow;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        footerLabel = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        headingLabel = new javax.swing.JLabel();
        headingPic = new javax.swing.JLabel();
        bodyPanel = new javax.swing.JPanel();
        MainTab = new javax.swing.JTabbedPane();
        homeTab = new javax.swing.JPanel();
        coachesTextField = new javax.swing.JButton();
        routesTextField = new javax.swing.JButton();
        townsTextField = new javax.swing.JButton();
        driversTextField = new javax.swing.JButton();
        toursTextField = new javax.swing.JButton();
        billsTextField = new javax.swing.JButton();
        passengersTextField = new javax.swing.JButton();
        hotelsTextField = new javax.swing.JButton();
        Pic = new javax.swing.JLabel();
        logInButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        aboutUsTab = new javax.swing.JPanel();
        aboutUsPanel = new javax.swing.JPanel();
        aboutLabel1 = new javax.swing.JLabel();
        aboutLablel2 = new javax.swing.JLabel();
        contactScroll = new javax.swing.JScrollPane();
        contactTextArea1 = new javax.swing.JTextArea();
        aboutLabel3 = new javax.swing.JLabel();
        aboutLabel4 = new javax.swing.JLabel();
        editTab = new javax.swing.JPanel();
        editScroll = new javax.swing.JScrollPane();
        editTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tour Management System");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        footerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/db/Image/Tour 4.jpg"))); // NOI18N

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));

        headingLabel.setBackground(new java.awt.Color(51, 51, 51));
        headingLabel.setFont(new java.awt.Font("Andalus", 1, 36)); // NOI18N
        headingLabel.setText("Welcome to the Tour Management System");

        headingPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/db/Image/Tour1.jpg"))); // NOI18N

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(headingPic, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(headerPanelLayout.createSequentialGroup()
                    .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 280, Short.MAX_VALUE)))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headingPic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(headingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
        );

        MainTab.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N

        coachesTextField.setText("Coaches");
        coachesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachesTextFieldActionPerformed(evt);
            }
        });

        routesTextField.setText("Routes");
        routesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routesTextFieldActionPerformed(evt);
            }
        });

        townsTextField.setText("Towns");
        townsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                townsTextFieldActionPerformed(evt);
            }
        });

        driversTextField.setText("Drivers");
        driversTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driversTextFieldActionPerformed(evt);
            }
        });

        toursTextField.setText("Tours");
        toursTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toursTextFieldActionPerformed(evt);
            }
        });

        billsTextField.setText("Bills");
        billsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billsTextFieldActionPerformed(evt);
            }
        });

        passengersTextField.setText("Passengers");
        passengersTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passengersTextFieldActionPerformed(evt);
            }
        });

        hotelsTextField.setText("Hotels");
        hotelsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotelsTextFieldActionPerformed(evt);
            }
        });

        Pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/db/Image/tour2.jpg"))); // NOI18N

        logInButton.setFont(new java.awt.Font("Andalus", 1, 12)); // NOI18N
        logInButton.setText("LOG IN");
        logInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInButtonActionPerformed(evt);
            }
        });

        registerButton.setFont(new java.awt.Font("Andalus", 1, 12)); // NOI18N
        registerButton.setText("REGISTER");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout homeTabLayout = new javax.swing.GroupLayout(homeTab);
        homeTab.setLayout(homeTabLayout);
        homeTabLayout.setHorizontalGroup(
            homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeTabLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeTabLayout.createSequentialGroup()
                        .addComponent(routesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(Pic))
                    .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(coachesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(townsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(driversTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toursTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(hotelsTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(passengersTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(billsTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(89, 89, 89)
                .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        homeTabLayout.setVerticalGroup(
            homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeTabLayout.createSequentialGroup()
                .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(homeTabLayout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(routesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hotelsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(townsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(11, 11, 11)
                            .addComponent(coachesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(homeTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(driversTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(toursTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(homeTabLayout.createSequentialGroup()
                            .addGap(91, 91, 91)
                            .addComponent(passengersTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(billsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(homeTabLayout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addComponent(Pic)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, homeTabLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(logInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        MainTab.addTab("Home", homeTab);

        aboutUsPanel.setBackground(new java.awt.Color(255, 255, 255));

        aboutLabel1.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        aboutLabel1.setText("CONTACT US NOW");

        aboutLablel2.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        aboutLablel2.setText("We are a leading Tour Sceduling Company in Sri Lanka");

        contactScroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        contactScroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        contactTextArea1.setEditable(false);
        contactTextArea1.setColumns(20);
        contactTextArea1.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        contactTextArea1.setRows(5);
        contactTextArea1.setText("Abc Company\n22, Galle Road,\nWellawatte\n0778866543");
        contactScroll.setViewportView(contactTextArea1);

        aboutLabel3.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        aboutLabel3.setText("We help to make your tour a memorable one.");

        aboutLabel4.setFont(new java.awt.Font("Andalus", 1, 24)); // NOI18N
        aboutLabel4.setText("All the tour packages are at affordable rate. Hotel Booking facilities available. ");

        javax.swing.GroupLayout aboutUsPanelLayout = new javax.swing.GroupLayout(aboutUsPanel);
        aboutUsPanel.setLayout(aboutUsPanelLayout);
        aboutUsPanelLayout.setHorizontalGroup(
            aboutUsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutUsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(aboutUsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aboutLablel2, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aboutLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aboutLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(aboutUsPanelLayout.createSequentialGroup()
                        .addComponent(aboutLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(contactScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        aboutUsPanelLayout.setVerticalGroup(
            aboutUsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutUsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aboutLablel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aboutLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(aboutLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(aboutUsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aboutLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout aboutUsTabLayout = new javax.swing.GroupLayout(aboutUsTab);
        aboutUsTab.setLayout(aboutUsTabLayout);
        aboutUsTabLayout.setHorizontalGroup(
            aboutUsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutUsTabLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(aboutUsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        aboutUsTabLayout.setVerticalGroup(
            aboutUsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutUsTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aboutUsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        MainTab.addTab("About Us", aboutUsTab);

        editTextArea.setEditable(false);
        editTextArea.setColumns(20);
        editTextArea.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        editTextArea.setRows(5);
        editTextArea.setText("\nPlease Log in to the system first to access the system and to add, edit, delete or view the details about a tour.\nIf you don`t have a account, please register to the system.\n\nAfter logging in to the system, by clicking the buttons in the home you can access various details and modify it.\nBy clicking the buttons in the home, you will get a window with tabs,where you can add, edit, delete or view by \nclicking each of the tabs\n");
        editScroll.setViewportView(editTextArea);

        javax.swing.GroupLayout editTabLayout = new javax.swing.GroupLayout(editTab);
        editTab.setLayout(editTabLayout);
        editTabLayout.setHorizontalGroup(
            editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editTabLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(editScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 931, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        editTabLayout.setVerticalGroup(
            editTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editTabLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(editScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        MainTab.addTab("Help", editTab);

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addComponent(MainTab, javax.swing.GroupLayout.PREFERRED_SIZE, 987, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainTab, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(footerLabel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(footerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void coachesTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachesTextFieldActionPerformed
        if (status == 1 || status == 2)
            new CoachWindow().setVisible(true);
        else if(status == 0)
            JOptionPane.showMessageDialog(null, "You must log in to the system first, to access this","INFORMATION",JOptionPane.ERROR_MESSAGE);
        else
            JOptionPane.showMessageDialog(null, "You don`t have enough privilleges, to access this","INFORMATION",JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_coachesTextFieldActionPerformed

    private void billsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billsTextFieldActionPerformed
        if (status == 1 || status == 4)
            BillWindow.create().setVisible(true);
        else if(status == 0)
            JOptionPane.showMessageDialog(null, "INFORMATION", "You must log in to the system first, to access this",JOptionPane.ERROR_MESSAGE);
        else
            JOptionPane.showMessageDialog(null, "INFORMATION", "You don`t have enough privilleges, to access this",JOptionPane.ERROR_MESSAGE);
        
       
    }//GEN-LAST:event_billsTextFieldActionPerformed

    private void driversTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driversTextFieldActionPerformed
        // TODO add your handling code here:
        if (status == 1 || status == 2)
            new DriverWindow().setVisible(true);
        
        else if(status == 0)
            JOptionPane.showMessageDialog(null,"You must log in to the system first, to access this","INFORMATION",JOptionPane.ERROR_MESSAGE);
        else
            JOptionPane.showMessageDialog(null,  "You don`t have enough privilleges, to access this","INFORMATION",JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_driversTextFieldActionPerformed

    private void hotelsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotelsTextFieldActionPerformed
        // TODO add your handling code here:
        if (status == 1 || status == 4)
            HotelsWindow.create().setVisible(true);
        else if(status == 0)
            JOptionPane.showMessageDialog(null, "You must log in to the system first, to access this","INFORMATION",JOptionPane.ERROR_MESSAGE);
        else
            JOptionPane.showMessageDialog(null,  "You don`t have enough privilleges, to access this","INFORMATION",JOptionPane.ERROR_MESSAGE);
      
    }//GEN-LAST:event_hotelsTextFieldActionPerformed

    private void townsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_townsTextFieldActionPerformed
        if(status == 1)
            new TownWindow().setVisible(true);
         else if(status == 0)
            JOptionPane.showMessageDialog(null, "You must log in to the system first, to access this","INFORMATION",JOptionPane.ERROR_MESSAGE);
        else
            JOptionPane.showMessageDialog(null, "You don`t have enough privilleges, to access this","INFORMATION",JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_townsTextFieldActionPerformed

    private void toursTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toursTextFieldActionPerformed
        if (status == 1 || status == 2 || status == 3)
            new TourWindow().setVisible(true);
        else if(status == 0)
            JOptionPane.showMessageDialog(null,  "You must log in to the system first, to access this","INFORMATION",JOptionPane.ERROR_MESSAGE);
        else
            JOptionPane.showMessageDialog(null,  "You don`t have enough privilleges, to access this","INFORMATION",JOptionPane.ERROR_MESSAGE);
   
    }//GEN-LAST:event_toursTextFieldActionPerformed

    private void passengersTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passengersTextFieldActionPerformed
        // TODO add your handling code here:
        if(status == 1 || status == 2|| status == 3)
            new PassengerWindow().setVisible(true);
        else if(status == 0)
            JOptionPane.showMessageDialog(null, "You must log in to the system first, to access this","INFORMATION",JOptionPane.ERROR_MESSAGE);
        else
            JOptionPane.showMessageDialog(null,  "You don`t have enough privilleges, to access this","INFORMATION",JOptionPane.ERROR_MESSAGE);
   
        
    }//GEN-LAST:event_passengersTextFieldActionPerformed

    private void routesTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routesTextFieldActionPerformed
        if(status == 1 || status == 2)
            RouteWindow.create().setVisible(true);
        else if(status == 0)
            JOptionPane.showMessageDialog(null,  "You must log in to the system first, to access this","INFORMATION",JOptionPane.ERROR_MESSAGE);
        else
            JOptionPane.showMessageDialog(null,  "You don`t have enough privilleges, to access this","INFORMATION",JOptionPane.ERROR_MESSAGE);
   
       
    }//GEN-LAST:event_routesTextFieldActionPerformed

    private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInButtonActionPerformed
        if(status == 0)
            new LogIn().setVisible(true);
        else    {
            status = 0;
            logInButton.setText("LOG IN");
        }
    }//GEN-LAST:event_logInButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        new SignUp().setVisible(true);
    }//GEN-LAST:event_registerButtonActionPerformed

    public void changeValue(String name, int status)   {
        loginSuccess = true;
        this.status = status;
        logInButton.setText("LOG OUT (user : " + name + " )");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        try {
        UIManager.setLookAndFeel("de.javasoft.plaf.synthetica.SyntheticaBlackStarLookAndFeel");
          
        } catch (ClassNotFoundException classNotFoundException) {
        } catch (InstantiationException instantiationException) {
        } catch (IllegalAccessException illegalAccessException) {
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane MainTab;
    private javax.swing.JLabel Pic;
    private javax.swing.JLabel aboutLabel1;
    private javax.swing.JLabel aboutLabel3;
    private javax.swing.JLabel aboutLabel4;
    private javax.swing.JLabel aboutLablel2;
    private javax.swing.JPanel aboutUsPanel;
    private javax.swing.JPanel aboutUsTab;
    private javax.swing.JButton billsTextField;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton coachesTextField;
    private javax.swing.JScrollPane contactScroll;
    private javax.swing.JTextArea contactTextArea1;
    private javax.swing.JButton driversTextField;
    private javax.swing.JScrollPane editScroll;
    private javax.swing.JPanel editTab;
    private javax.swing.JTextArea editTextArea;
    private javax.swing.JLabel footerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JLabel headingPic;
    private javax.swing.JPanel homeTab;
    private javax.swing.JButton hotelsTextField;
    private javax.swing.JButton logInButton;
    private javax.swing.JButton passengersTextField;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton routesTextField;
    private javax.swing.JButton toursTextField;
    private javax.swing.JButton townsTextField;
    // End of variables declaration//GEN-END:variables
}
