package db.entity;
// Generated Mar 12, 2014 5:01:43 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Coach generated by hbm2java
 */
public class Coach  implements java.io.Serializable {


     private int regNo;
     private int capacity;
     private Date lastServiceDate;
     private Double lastServiceMileage;
     private Set tours = new HashSet(0);

    public Coach() {
    }

	
    public Coach(int regNo, int capacity) {
        this.regNo = regNo;
        this.capacity = capacity;
    }
    public Coach(int regNo, int capacity, Date lastServiceDate, Double lastServiceMileage, Set tours) {
       this.regNo = regNo;
       this.capacity = capacity;
       this.lastServiceDate = lastServiceDate;
       this.lastServiceMileage = lastServiceMileage;
       this.tours = tours;
    }
   
    public int getRegNo() {
        return this.regNo;
    }
    
    public void setRegNo(int regNo) {
        this.regNo = regNo;
    }
    public int getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(int capacity) {
        this.capacity = capacity;
    }
    public Date getLastServiceDate() {
        return this.lastServiceDate;
    }
    
    public void setLastServiceDate(Date lastServiceDate) {
        this.lastServiceDate = lastServiceDate;
    }
    public Double getLastServiceMileage() {
        return this.lastServiceMileage;
    }
    
    public void setLastServiceMileage(Double lastServiceMileage) {
        this.lastServiceMileage = lastServiceMileage;
    }
    public Set getTours() {
        return this.tours;
    }
    
    public void setTours(Set tours) {
        this.tours = tours;
    }




}


