package db.entity;
// Generated Mar 12, 2014 5:01:43 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Driver generated by hbm2java
 */
public class Driver  implements java.io.Serializable {


     private DriverId id;
     private String address;
     private String tpNo;
     private Set driverRoutes = new HashSet(0);
     private Set tours = new HashSet(0);

    public Driver() {
    }

	
    public Driver(DriverId id, String address, String tpNo) {
        this.id = id;
        this.address = address;
        this.tpNo = tpNo;
    }
    public Driver(DriverId id, String address, String tpNo, Set driverRoutes, Set tours) {
       this.id = id;
       this.address = address;
       this.tpNo = tpNo;
       this.driverRoutes = driverRoutes;
       this.tours = tours;
    }
   
    public DriverId getId() {
        return this.id;
    }
    
    public void setId(DriverId id) {
        this.id = id;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getTpNo() {
        return this.tpNo;
    }
    
    public void setTpNo(String tpNo) {
        this.tpNo = tpNo;
    }
    public Set getDriverRoutes() {
        return this.driverRoutes;
    }
    
    public void setDriverRoutes(Set driverRoutes) {
        this.driverRoutes = driverRoutes;
    }
    public Set getTours() {
        return this.tours;
    }
    
    public void setTours(Set tours) {
        this.tours = tours;
    }




}


