package db.entity;
// Generated Mar 15, 2014 11:52:23 AM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Driver generated by hbm2java
 */
public class Driver implements java.io.Serializable {

    private DriverId id;
    private String address;
    private String tpNo;
    private Set driverRoutes = new HashSet(0);
    private Set tours = new HashSet(0);

    public Driver() {
    }

    public Driver(DriverId id, String address, String tpNo) {
        this.id = id;
        this.address = address;
        this.tpNo = tpNo;
    }

    public Driver(DriverId id, String address, String tpNo, Set driverRoutes, Set tours) {
        this.id = id;
        this.address = address;
        this.tpNo = tpNo;
        this.driverRoutes = driverRoutes;
        this.tours = tours;
    }

    public DriverId getId() {
        return this.id;
    }

    public void setId(DriverId id) {
        this.id = id;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getTpNo() {
        return this.tpNo;
    }

    public void setTpNo(String tpNo) {
        this.tpNo = tpNo;
    }

    public Set getDriverRoutes() {
        return this.driverRoutes;
    }

    public void setDriverRoutes(Set driverRoutes) {
        this.driverRoutes = driverRoutes;
    }

    public Set getTours() {
        return this.tours;
    }

    public void setTours(Set tours) {
        this.tours = tours;
    }

    @Override
    public String toString() {
        return id.toString();
    }

    @Override
    public int hashCode() {
        int hash = 7;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Driver other = (Driver) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }

}
