package db.entity;
// Generated Mar 9, 2014 1:58:00 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Hotels generated by hbm2java
 */
public class Hotels  implements java.io.Serializable {


     private int id;
     private Towns towns;
     private String name;
     private Set billses = new HashSet(0);

    public Hotels() {
    }

	
    public Hotels(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Hotels(int id, Towns towns, String name, Set billses) {
       this.id = id;
       this.towns = towns;
       this.name = name;
       this.billses = billses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Towns getTowns() {
        return this.towns;
    }
    
    public void setTowns(Towns towns) {
        this.towns = towns;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getBillses() {
        return this.billses;
    }
    
    public void setBillses(Set billses) {
        this.billses = billses;
    }




}


