package db.entity;
// Generated Mar 12, 2014 5:01:43 PM by Hibernate Tools 3.6.0



/**
 * Passenger generated by hbm2java
 */
public class Passenger  implements java.io.Serializable {


     private int id;
     private Tour tour;
     private String name;

    public Passenger() {
    }

	
    public Passenger(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Passenger(int id, Tour tour, String name) {
       this.id = id;
       this.tour = tour;
       this.name = name;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Tour getTour() {
        return this.tour;
    }
    
    public void setTour(Tour tour) {
        this.tour = tour;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Override
    public String toString() {
        return  id + " - " + name;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Passenger other = (Passenger) obj;
        if (this.id != other.id) {
            return false;
        }
        return true;
    }
    
    
}


