package db.entity;
// Generated Mar 15, 2014 11:52:23 AM by Hibernate Tools 3.6.0

/**
 * RouteTownId generated by hbm2java
 */
public class RouteTownId implements java.io.Serializable {

    private Integer routeId;
    private Integer townId;

    public RouteTownId() {
    }

    public RouteTownId(Integer routeId, Integer townId) {
        this.routeId = routeId;
        this.townId = townId;
    }

    public Integer getRouteId() {
        return this.routeId;
    }

    public void setRouteId(Integer routeId) {
        this.routeId = routeId;
    }

    public Integer getTownId() {
        return this.townId;
    }

    public void setTownId(Integer townId) {
        this.townId = townId;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof RouteTownId)) {
            return false;
        }
        RouteTownId castOther = (RouteTownId) other;

        return ((this.getRouteId() == castOther.getRouteId()) || (this.getRouteId() != null && castOther.getRouteId() != null && this.getRouteId().equals(castOther.getRouteId())))
                && ((this.getTownId() == castOther.getTownId()) || (this.getTownId() != null && castOther.getTownId() != null && this.getTownId().equals(castOther.getTownId())));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (getRouteId() == null ? 0 : this.getRouteId().hashCode());
        result = 37 * result + (getTownId() == null ? 0 : this.getTownId().hashCode());
        return result;
    }

}
