package db.entity;
// Generated Mar 9, 2014 1:58:00 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Routes generated by hbm2java
 */
public class Routes  implements java.io.Serializable {


     private int id;
     private String name;
     private Integer days;
     private Integer distance;
     private Set townses = new HashSet(0);
     private Set tourses = new HashSet(0);
     private Set driverses = new HashSet(0);

    public Routes() {
    }

	
    public Routes(int id) {
        this.id = id;
    }
    public Routes(int id, String name, Integer days, Integer distance, Set townses, Set tourses, Set driverses) {
       this.id = id;
       this.name = name;
       this.days = days;
       this.distance = distance;
       this.townses = townses;
       this.tourses = tourses;
       this.driverses = driverses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getDays() {
        return this.days;
    }
    
    public void setDays(Integer days) {
        this.days = days;
    }
    public Integer getDistance() {
        return this.distance;
    }
    
    public void setDistance(Integer distance) {
        this.distance = distance;
    }
    public Set getTownses() {
        return this.townses;
    }
    
    public void setTownses(Set townses) {
        this.townses = townses;
    }
    public Set getTourses() {
        return this.tourses;
    }
    
    public void setTourses(Set tourses) {
        this.tourses = tourses;
    }
    public Set getDriverses() {
        return this.driverses;
    }
    
    public void setDriverses(Set driverses) {
        this.driverses = driverses;
    }




}


