package db.entity;
// Generated Mar 15, 2014 11:52:23 AM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * Route generated by hbm2java
 */
public class Route implements java.io.Serializable {

    private int id;
    private String name;
    private Integer days;
    private Integer distance;
    private Set driverRoutes = new HashSet(0);
    private Set tours = new HashSet(0);
    private Set routeTowns = new HashSet(0);

    public Route() {
    }

    public Route(int id) {
        this.id = id;
    }

    public Route(int id, String name, int days, int distance) {
        this.id = id;
        this.name = name;
        this.days = days;
        this.distance = distance;

    }

    public Route(int id, String name, Integer days, Integer distance, Set driverRoutes, Set tours, Set routeTowns) {
        this.id = id;
        this.name = name;
        this.days = days;
        this.distance = distance;
        this.driverRoutes = driverRoutes;
        this.tours = tours;
        this.routeTowns = routeTowns;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getDays() {
        return this.days;
    }

    public void setDays(Integer days) {
        this.days = days;
    }

    public Integer getDistance() {
        return this.distance;
    }

    public void setDistance(Integer distance) {
        this.distance = distance;
    }

    public Set getDriverRoutes() {
        return this.driverRoutes;
    }

    public void setDriverRoutes(Set driverRoutes) {
        this.driverRoutes = driverRoutes;
    }

    public Set getTours() {
        return this.tours;
    }

    public void setTours(Set tours) {
        this.tours = tours;
    }

    public Set getRouteTowns() {
        return this.routeTowns;
    }

    public void setRouteTowns(Set routeTowns) {
        this.routeTowns = routeTowns;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Route other = (Route) obj;
        if (this.id != other.id) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return id + " - " + name;
    }

}
