package db.entity;
// Generated Mar 10, 2014 2:54:58 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Route generated by hbm2java
 */
public class Route  implements java.io.Serializable {


     private int id;
     private String name;
     private Integer days;
     private Integer distance;
     private Set driverRoutes = new HashSet(0);
     private Set tours = new HashSet(0);
     private Set routeTowns = new HashSet(0);

    public Route() {
    }

	
    public Route(int id) {
        this.id = id;
    }
    public Route(int id, String name, Integer days, Integer distance, Set driverRoutes, Set tours, Set routeTowns) {
       this.id = id;
       this.name = name;
       this.days = days;
       this.distance = distance;
       this.driverRoutes = driverRoutes;
       this.tours = tours;
       this.routeTowns = routeTowns;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getDays() {
        return this.days;
    }
    
    public void setDays(Integer days) {
        this.days = days;
    }
    public Integer getDistance() {
        return this.distance;
    }
    
    public void setDistance(Integer distance) {
        this.distance = distance;
    }
    public Set getDriverRoutes() {
        return this.driverRoutes;
    }
    
    public void setDriverRoutes(Set driverRoutes) {
        this.driverRoutes = driverRoutes;
    }
    public Set getTours() {
        return this.tours;
    }
    
    public void setTours(Set tours) {
        this.tours = tours;
    }
    public Set getRouteTowns() {
        return this.routeTowns;
    }
    
    public void setRouteTowns(Set routeTowns) {
        this.routeTowns = routeTowns;
    }




}


