package db.entity;
// Generated Mar 9, 2014 1:58:00 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tours generated by hbm2java
 */
public class Tours  implements java.io.Serializable {


     private int tourCode;
     private Routes routes;
     private Coaches coaches;
     private Drivers drivers;
     private Date startDate;
     private String executed;
     private Set billses = new HashSet(0);

    public Tours() {
    }

	
    public Tours(int tourCode) {
        this.tourCode = tourCode;
    }
    public Tours(int tourCode, Routes routes, Coaches coaches, Drivers drivers, Date startDate, String executed, Set billses) {
       this.tourCode = tourCode;
       this.routes = routes;
       this.coaches = coaches;
       this.drivers = drivers;
       this.startDate = startDate;
       this.executed = executed;
       this.billses = billses;
    }
   
    public int getTourCode() {
        return this.tourCode;
    }
    
    public void setTourCode(int tourCode) {
        this.tourCode = tourCode;
    }
    public Routes getRoutes() {
        return this.routes;
    }
    
    public void setRoutes(Routes routes) {
        this.routes = routes;
    }
    public Coaches getCoaches() {
        return this.coaches;
    }
    
    public void setCoaches(Coaches coaches) {
        this.coaches = coaches;
    }
    public Drivers getDrivers() {
        return this.drivers;
    }
    
    public void setDrivers(Drivers drivers) {
        this.drivers = drivers;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public String getExecuted() {
        return this.executed;
    }
    
    public void setExecuted(String executed) {
        this.executed = executed;
    }
    public Set getBillses() {
        return this.billses;
    }
    
    public void setBillses(Set billses) {
        this.billses = billses;
    }




}


