package db.entity;
// Generated Mar 9, 2014 1:58:00 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Towns generated by hbm2java
 */
public class Towns  implements java.io.Serializable {


     private int id;
     private String name;
     private Set routeses = new HashSet(0);
     private Set billses = new HashSet(0);
     private Set hotelses = new HashSet(0);

    public Towns() {
    }

	
    public Towns(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public Towns(int id, String name, Set routeses, Set billses, Set hotelses) {
       this.id = id;
       this.name = name;
       this.routeses = routeses;
       this.billses = billses;
       this.hotelses = hotelses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getRouteses() {
        return this.routeses;
    }
    
    public void setRouteses(Set routeses) {
        this.routeses = routeses;
    }
    public Set getBillses() {
        return this.billses;
    }
    
    public void setBillses(Set billses) {
        this.billses = billses;
    }
    public Set getHotelses() {
        return this.hotelses;
    }
    
    public void setHotelses(Set hotelses) {
        this.hotelses = hotelses;
    }




}


