package db.entity;
// Generated Mar 24, 2014 9:30:15 AM by Hibernate Tools 3.6.0



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private String name;
     private String password;
     private int privilege;

    public User() {
    }

    public User(String name, String password, int privilege) {
       this.name = name;
       this.password = password;
       this.privilege = privilege;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getPrivilege() {
        return this.privilege;
    }
    
    public void setPrivilege(int privilege) {
        this.privilege = privilege;
    }




}


