package db.ui.panels;

import db.dao.TourDAO;
import db.entity.Tour;
import java.awt.Container;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Gobinath
 */
public class TourSearchPanel extends javax.swing.JPanel {

    private final TourDAO tourDAO;
    private static TourSearchPanel instance;

    /**
     * Creates new form TownEditPanel
     */
    private TourSearchPanel() {
        initComponents();
        tourDAO = new TourDAO();
    }

    public static TourSearchPanel getInstance() {
        if (instance == null) {
            instance = new TourSearchPanel();
        }
        return instance;
    }

    public void refresh() {
        tableView.setModel(new javax.swing.table.DefaultTableModel(null, new String[]{"Tour Code", "Route", "Coach", "Start Date", "Executed", "Driver", "No of Bills", "No of Passengers"}));
        txtTourCode.setText("");
        txtTourCode.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelScroll = new javax.swing.JScrollPane();
        panelMain = new javax.swing.JPanel();
        panelDetails = new javax.swing.JPanel();
        lblTownID = new javax.swing.JLabel();
        txtTourCode = new javax.swing.JTextField();
        panelBills = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableView = new javax.swing.JTable();
        panelControlls = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panelDetails.setBorder(javax.swing.BorderFactory.createTitledBorder("Details"));
        panelDetails.setName(""); // NOI18N

        lblTownID.setText("Tour Code");

        javax.swing.GroupLayout panelDetailsLayout = new javax.swing.GroupLayout(panelDetails);
        panelDetails.setLayout(panelDetailsLayout);
        panelDetailsLayout.setHorizontalGroup(
            panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTownID)
                .addGap(38, 38, 38)
                .addComponent(txtTourCode)
                .addGap(5, 5, 5))
        );
        panelDetailsLayout.setVerticalGroup(
            panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTownID)
                    .addComponent(txtTourCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBills.setBorder(javax.swing.BorderFactory.createTitledBorder("Result"));
        panelBills.setName(""); // NOI18N
        panelBills.setPreferredSize(new java.awt.Dimension(30, 30));
        panelBills.setLayout(new javax.swing.BoxLayout(panelBills, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane5.setPreferredSize(new java.awt.Dimension(300, 200));

        tableView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tour Code", "Route", "Coach", "Start Date", "Executed", "Bills", "Passengers"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableView.setPreferredSize(new java.awt.Dimension(100, 0));
        tableView.getTableHeader().setReorderingAllowed(false);
        tableView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableViewMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tableView);

        panelBills.add(jScrollPane5);

        panelControlls.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelControllsLayout = new javax.swing.GroupLayout(panelControlls);
        panelControlls.setLayout(panelControllsLayout);
        panelControllsLayout.setHorizontalGroup(
            panelControllsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelControllsLayout.createSequentialGroup()
                .addContainerGap(333, Short.MAX_VALUE)
                .addComponent(btnClear)
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addContainerGap())
        );
        panelControllsLayout.setVerticalGroup(
            panelControllsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelControllsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelControllsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(btnClear))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelControlls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBills, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(panelDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(panelBills, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(panelControlls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        panelScroll.setViewportView(panelMain);

        add(panelScroll, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String strID = txtTourCode.getText();
        List<Tour> result = null;
        Integer id = null;
        if (!strID.equals("")) {
            try {
                id = Integer.valueOf(strID);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Please enter valid tour code", "Warning", JOptionPane.WARNING_MESSAGE);
                txtTourCode.selectAll();
                txtTourCode.requestFocus();
                return;
            }
            result = tourDAO.getTours(id);
        } else {
            result = tourDAO.getAllTours();
        }

        if (result == null || result.size() == 0) {
            JOptionPane.showMessageDialog(this, "No data found", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            createViewTable(result);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void tableViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableViewMouseClicked
        if (evt.getClickCount() == 2) {
            int id = Integer.parseInt(tableView.getValueAt(tableView.getSelectedRow(), 0).toString());
            TourEditPanel panel = TourEditPanel.getInstance();
            panel.refresh(tourDAO.getTour(id));
            Container container = this.getParent();
            container.removeAll();
            container.add(panel);
            container.repaint();
            container.validate();
        }
    }//GEN-LAST:event_tableViewMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        refresh();
    }//GEN-LAST:event_btnClearActionPerformed

    private void createViewTable(List<Tour> tours) {
        ArrayList<Object[]> data = new ArrayList<>();
        try {
            for (int i = 0; i < tours.size(); i++) {
                Object[] row = new Object[]{tours.get(i).getTourCode(), tours.get(i).getRoute(), tours.get(i).getCoach(),
                    tours.get(i).getStartDate(), tours.get(i).getExecuted(), tours.get(i).getDriver(), tours.get(i).getBills().size(), tours.get(i).getPassengers().size()};
                data.add(row);
            }
            Object[][] passengerData = data.toArray(new Object[0][]);
            tableView.setModel(new javax.swing.table.DefaultTableModel(
                    passengerData,
                    new String[]{
                        "Tour Code", "Route", "Coach", "Start Date", "Executed", "Driver", "No of Bills", "No of Passengers"
                    }
            ) {
                boolean[] canEdit = new boolean[]{
                    false, false, false, false, false, false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            });
            tableView.setAutoscrolls(true);
            tableView.setFillsViewportHeight(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSearch;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblTownID;
    private javax.swing.JPanel panelBills;
    private javax.swing.JPanel panelControlls;
    private javax.swing.JPanel panelDetails;
    private javax.swing.JPanel panelMain;
    private javax.swing.JScrollPane panelScroll;
    private javax.swing.JTable tableView;
    private javax.swing.JTextField txtTourCode;
    // End of variables declaration//GEN-END:variables
}
